/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dashboard": [],
    "users.index": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.index": [],
    "companies.store": [],
    "companies.show": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.update": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.destroy": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.index": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.index": [],
    "designations.store": [],
    "designations.show": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.update": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.destroy": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.index": [],
    "employees.store": [],
    "employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "logout": [],
    "login": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
