/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        }
    ],
    "debugbar.queries.explain": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets": [],
    "dashboard": [],
    "users.index": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.index": [],
    "companies.store": [],
    "companies.show": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.update": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "companies.destroy": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.index": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.index": [],
    "designations.store": [],
    "designations.show": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.update": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "designations.destroy": [
        {
            "name": "designation",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.index": [],
    "employees.store": [],
    "employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "shifts.index": [],
    "shifts.store": [],
    "shifts.show": [
        {
            "name": "shift",
            "required": true
        }
    ],
    "shifts.update": [
        {
            "name": "shift",
            "required": true,
            "binding": "id"
        }
    ],
    "shifts.destroy": [
        {
            "name": "shift",
            "required": true,
            "binding": "id"
        }
    ],
    "rosters.bulkDelete": [],
    "rosters.index": [],
    "rosters.store": [],
    "rosters.show": [
        {
            "name": "roster",
            "required": true,
            "binding": "id"
        }
    ],
    "rosters.update": [
        {
            "name": "roster",
            "required": true,
            "binding": "id"
        }
    ],
    "rosters.destroy": [
        {
            "name": "roster",
            "required": true,
            "binding": "id"
        }
    ],
    "attendance.bulkDelete": [],
    "attendance.index": [],
    "attendance.store": [],
    "attendance.show": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "attendance.update": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "attendance.destroy": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "defaults.index": [],
    "defaults.store": [],
    "defaults.show": [
        {
            "name": "default",
            "required": true
        }
    ],
    "defaults.update": [
        {
            "name": "default",
            "required": true,
            "binding": "id"
        }
    ],
    "defaults.destroy": [
        {
            "name": "default",
            "required": true,
            "binding": "id"
        }
    ],
    "deductions.generateSalary": [],
    "deductions.index": [],
    "deductions.store": [],
    "deductions.show": [
        {
            "name": "deduction",
            "required": true,
            "binding": "id"
        }
    ],
    "deductions.update": [
        {
            "name": "deduction",
            "required": true,
            "binding": "id"
        }
    ],
    "deductions.destroy": [
        {
            "name": "deduction",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.index": [],
    "pdf.bio-data": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.t-and-c": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.appointment-order": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.induction-training": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.form-v": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.form-f": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.form-2": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.esic": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.form-34": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.form-25b": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.timing-report": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "pdf.attendance-report": [
        {
            "name": "company",
            "required": true,
            "binding": "id"
        }
    ],
    "logout": [],
    "login": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
